linux_docker_builder:
  script: docker build -t $CIRRUS_REPO_FULL_NAME:cirrus-linux . -f Dockerfile

linuxarmv7_docker_builder:
  script: docker build -t $CIRRUS_REPO_FULL_NAME:cirrus-rpi . -f Dockerfile.rpi

linuxarmv6_docker_builder:    
  script: docker build -t $CIRRUS_REPO_FULL_NAME:cirrus-armv6 . -f Dockerfile.rpi --build-arg ARCH=armv6l

linuxarm64_docker_builder:    
  script: |
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    docker build -t $CIRRUS_REPO_FULL_NAME:cirrus-arm64 . -f Dockerfile.arm64
